---
name: vars-finder

on:
  push:
    branches:
      - main
    paths: ["vars"]
    tags:
      - '*'
      
env:
  BUILD_ARGS: |
          BUILD_REF
          BUILD_ARCH
          BUILD_NAME
          BUILD_VERSION
          

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Vars via Env Var
        run: echo "The var is $GITHUB_REF_NAME"

      - name: Display Vars via Github Context
        run: echo "The Var is ${{ github.event.release.tag_name }}"

      
